### ISSUE TITLE
Is the buffer "distance" argument in meters?

### ISSUE THREAD

**Issue by sirrodgepodge** [simplegeo/jts#3]
Guessing yes given the conversion that happens in this javascript library here (`turf-jsts` which is used for the `BufferOp.bufferOp` call is a JS library very similar to this one):
https://github.com/Turfjs/turf/blob/17002ccd57e04e84ddb38d7e3ac8ede35b019c58/packages/turf-buffer/index.js#L114

if the unit of "distance" is "meters" it would be great to document this somewhere

**Comment by sirrodgepodge** [comment]
ahh learning a lot, looks like the default is degrees but can turn it into meters by setting SRID :)

**Comment by alexovidiupopa** [comment]
The greatness of having it documented still holds true. 😄
